### ISSUE TITLE
Command line options are obsure and interfere with user ones

### ISSUE THREAD

**Issue by adinapoli** [hspec/hspec#135]
(Maybe I'm ignoring something here, which might make the whole issue moot).

Let's image I'm a beginner which doesn't know much about Haskell or Hspec. I want to pass some command line arguments to my test executable, to do some pre/post process (e.g. clear the DB) according to a value I pass in. The code to accomplish this is:

``` haskell
main :: IO ()
main = do
  [env] <- getArgs
  withFreshDB env "news"
  hspec newsSpec
```

But when I try this, I get:

```
─$ testsuite prod
testsuite: unexpected argument `prod'
Try `testsuite --help' for more information.
```

For the beginner, this is confusing. There is no documentation on why I should get this error, I'm just calling "getArgs" at the end of the day!

After all the pantomime, the problem is in the way we currently handle `Options`. The incriminated function is:

``` haskell
hspecWithOptions :: Options -> Spec -> IO ()
hspecWithOptions opts spec = do
  prog <- getProgName
  args <- getArgs
  c <- getConfig opts prog args
  withArgs [] {- do not leak command-line arguments to examples -} $ do
    r <- hspecWith c spec
    unless (summaryFailures r == 0) exitFailure
```

Which call `getArgs`, getting all my command line arguments, and then calling `getConfig`:

``` haskell
getConfig :: Options -> String -> [String] -> IO Config
getConfig opts_ prog args = do
  case parseOptions opts_ prog args of
    Left (err, msg) -> exitWithMessage err msg
    Right opts -> do
      r <- if optionsRerun opts then readFailureReport else return Nothing
      return (mkConfig r opts)
```

which call `parseOptions`:

``` haskell
parseOptions :: Options -> String -> [String] -> Either (ExitCode, String) Options
parseOptions c prog args = case getOpt Permute (options ++ undocumentedOptions) args of
    (opts, [], []) -> case foldl' (flip id) (Right c) opts of
        Left Help                         -> Left (ExitSuccess, usageInfo ("Usage: " ++ prog ++ " [OPTION]...\n\nOPTIONS") options)
        Left (InvalidArgument flag value) -> tryHelp ("invalid argument `" ++ value ++ "' for `--" ++ flag ++ "'\n")
        Right x -> Right x
    (_, _, err:_)  -> tryHelp err
    (_, arg:_, _)  -> tryHelp ("unexpected argument `" ++ arg ++ "'\n")
  where
    tryHelp msg = Left (ExitFailure 1, prog ++ ": " ++ msg ++ "Try `" ++ prog ++ " --help' for more information.\n")
```

Which finally shed some light on the laconic error the beginner was getting.
I think this is a bit problematic; I do recognise the importance of providing the user which flags to allow him to tweak Hspec Summary look and feel, but I find very restrictive not be able to pass my own command line arguments; in fact, it's almost a deal breaker!

Last but not least, the Hspec documentation neither talk anywhere about Options nor tells you how to customise them. But customise them means just tweaking default values for a fixed data structure, without possibility to add mine.
Have you ever thought about that? Have you ever had the need to scratch such a itch?

Many thanks,
Alfredo

**Comment by liftM** [comment]
I just spent about half an hour tearing my hair out trying to figure out why my test's option parser wasn't working before I finally figured this out.

My test runner consumes its own flags to configure secrets that are used as part of the integration test. The code looks something like:

```hs
opts :: ParserInfo Options

main :: IO ()
main = do
  secrets <- execParser opts
  hspec $ runTestWithSecrets secrets

runTestWithSecrets :: Options -> Spec
```

The way this manifested for me was that passing my options would cause a "unrecognized option" failure from `hspec` (which says `Try --help for more information`), while passing `--help` would cause the output to display my own options (not the HSpec options) because the `--help` flag would be consumed by my own `execParser`, which would exit early! I thought I was going crazy.

I'm a relative newcomer to Haskell, and I wasn't aware of `withArgs` until I came across this thread. I would love if a section were added to the options documentation providing guidance on how to write tests that consume their own options.
