### ISSUE TITLE
Cannot return `IO Summary` without using `getArgs` after  `1.9.3`

### ISSUE THREAD

**Issue by PierreR** [hspec/hspec#215]
Hi,

I am trying to upgrade hspec from `1.9.2` to `2.x` in `language-puppet`. Here is the bit of code https://github.com/bartavelle/language-puppet/blob/master/Puppet/Testing.hs#L66

My first try was this commit 
https://github.com/bartavelle/language-puppet/commit/c417143907ab69217dfee2544c8ff907cf33cf76#diff-f098d10730d46183c4f2b6b0d0a237c4

It strangely fails with `puppetresources: unrecognized option `-p'`

I guess this is due to the new `getArgs` call here: https://github.com/hspec/hspec/blob/master/hspec-core/src/Test/Hspec/Core/Runner.hs#L118

At this point I am kind of stuck. What would be the transition path ?

Thanks for your help.

**Comment by sol** [comment]
@PierreR I'm super sorry for the late response.  I'll look at it tomorrow (Singapore time).  If it's about hiding command-line arguments from Hspec, then `withArgs` from `System.Environment` may be the way to go.

**Comment by sol** [comment]
@PierreR You removed that file, right?  Is there still something you need help with?

**Comment by PierreR** [comment]
Yep we have decided to remove hlint altogether for the use case at hand.

So I don't have any need for this anymore and you can close the issue as far as I am concerned.

I still believe the call to `getArgs` is a bit wierd though (and the user case seems legitimate to me) so if it can be replaced by something better, I guess it is a real plus for `hspec`.

Thanks for your quick feedback !

**Comment by sol** [comment]
The reason why the existing primitive uses `getArgs` is because this way you can provide your own default options, but you can still pass command-line arguments to your specs (e.g. only running specific specs).

I'm don't have a proper picture of the use case yet.  But if we don't want the current behavior (and if it's not possible to remedy this with `withArgs`), then we would probably add an other primitive that does not use `getArgs`.  If it is about being able to specify custom command-line options for your specs, we could also consider to add support for custom options.

**Comment by PierreR** [comment]
So the idea was to compute testing properties using `hspec` but inside another command line tool (named `puppetresources`) that has its own options. So we were using `hspec` more as a library.

**Comment by sol** [comment]
I think it that case you can just do something like

```haskell
main = do
  args <- getArgs
  ....
  withArgs [] . hspec $ ...
```

which basically hides any command-line arguments from Hspec.

Medium-term we could also add some primitive that does not do any command-line handling to `Test.Hspec.Core.Runner`.

**Comment by sol** [comment]
I created #216, closing.
