### ISSUE TITLE
aroundAll

### ISSUE THREAD

**Issue by radix** [hspec/hspec#255]
We have beforeAll and afterAll, but no aroundAll. I'm not sure if I'm missing something but I think that would be useful.

**Comment by sol** [comment]
The reason that there is no `aroundAll` is, that it is hard to implement, especially in the light of parallel test execution.

If we want to give it a try, a first step could be to implement a small standalone proof of concept.

**Comment by jfischoff** [comment]
Hi @sol 

We wrote the following definition at SimSpace

```

**Comment by sol** [comment]
Hey, this looks great! How about replacing the threadDelay with another takeMVar and the Async.cancel with a `putMVar ()`?

PR would be neat. I'd still want to spend some time to reason how this behaves for corner cases like exceptions, ctrl-c, etc.

**Comment by jfischoff** [comment]
This is the current version I am copying around in projects. I don't think the version above handles exceptions in the `withFunc` correctly:

```haskell
aroundAll :: forall a. ((a -> IO ()) -> IO ()) -> SpecWith a -> Spec
aroundAll withFunc specWith = do
  (var, stopper, asyncer) <- runIO $
    (,,) <$> newEmptyMVar <*> newEmptyMVar <*> newIORef Nothing
  let theStart :: IO a
      theStart = do

        thread <- async $ do
          withFunc $ \x -> do
            putMVar var x
            takeMVar stopper
          pure $ error "Don't evaluate this"

        writeIORef asyncer $ Just thread

        either pure pure =<< (wait thread `race` takeMVar var)

      theStop :: a -> IO ()
      theStop _ = do
        putMVar stopper ()
        traverse_ cancel =<< readIORef asyncer

  beforeAll theStart $ afterAll theStop $ specWith
```

**Comment by parsonsmatt** [comment]
Thanks @jfischoff , copying that into my own project. Will credit :)

**Comment by NorfairKing** [comment]
I've been looking for this for a while now, cool!!
This may also solve the problem I've had with shrinking. (I've had to use `withMaxShrinks (const 0)` or so to make sure that I would get accurate test faliures when using `around`.)

**Comment by chrisdone** [comment]
This one implements `aroundAllWith` and gets `aroundAll` as a freebie. 

```haskell
-- | Perform an action around the set of tests.

module Test.Hspec.AroundAll where

import Control.Concurrent
import Control.Concurrent.Async
import Test.Hspec
import Test.Hspec.Core.Hooks

-- | Wrap an action around the given spec.
aroundAll :: (ActionWith a -> IO ()) -> SpecWith a -> Spec
aroundAll actionWithAToUnit = aroundAllWith (const . actionWithAToUnit)

-- | Wrap an action around the given spec. Changes the arg type inside.
aroundAllWith :: (ActionWith a -> ActionWith b) -> SpecWith a -> SpecWith b
aroundAllWith actionWithAToB specWithA = do
  done <- runIO newEmptyMVar
  beforeAllWith
    (\b -> do
       -- The mutable reference is needed because @actionWithAToB@
       -- returns a @b@, not an @a@, as we'd like.
       mvarA <- newEmptyMVar
       -- The async thread is needed because @actionWithAToB@
       -- allocates and then /frees/ the resource, so we should block
       -- it from doing so until @afterAll@ has executed. Hence the
       -- @done@ var.
       blocker <-
         async
           (actionWithAToB
              (\a -> do
                 -- We make the a value immediately available to the
                 -- @takeMVar@ below, to be passed to @specWithA@ down
                 -- the road.
                 putMVar mvarA a
                 -- Wait for the test to be done before allowing
                 -- @actionWithAToB@ to clean up resources.
                 takeMVar done)
              b)
       -- If @actionWithAToB@ fails then it should rethrow the
       -- exception to this thread before we try to @takeMVar@ on a
       -- var that will never be filled. This gives better error
       -- messages than a "blocked indefinitely".
       link blocker
       takeMVar mvarA)
    (afterAll (const (putMVar done ())) specWithA)
```

**Comment by thomasjm** [comment]
@chrisdone FYI I just noticed that your implementation doesn't handle nesting the way one might expect. Consider the following:

```haskell
aroundWithFn action () = do
  putStrLn "aroundWith before"
  action ()
  putStrLn "aroundWith after"

aroundAllWithFn action () = do
  putStrLn "aroundAllWith before"
  action ()
  putStrLn "aroundAllWith after"

main = hspec $ aroundWith aroundWithFn $ aroundAllWith aroundAllWithFn $ do
  it "does item A" $ 2 `shouldBe` 2
  it "does item B" $ 2 `shouldBe` 2

main2 = hspec $ aroundAllWith aroundAllWithFn $ aroundWith aroundWithFn $ do
  it "does item A" $ 2 `shouldBe` 2
  it "does item B" $ 2 `shouldBe` 2
```

When you run `main`, you get

```
aroundWith before
aroundAllWith before
aroundWith after
does item A
aroundWith before
aroundWith after
does item B
aroundWith before
aroaurnoduWnidtAhl laWfittehr 
afte
r
```

Ignoring the racing prints at the end, the first 3 lines show a violation of the nesting property that the Hspec `around*` hooks otherwise obey. For most purposes it shouldn't matter, but I was trying to use hooks like this to generate profiling data (by treating each hook as a "stack frame") and getting invalid traces because the frames don't properly nest.

Running `main2` produces the desired result though.

**Comment by chrisdone** [comment]
You can use `Data.ByteString.putStrLn` to get an atomic print to avoid the garbled output. 

```
aroundWith before
aroundAllWith before
aroundWith after
```

What order did you expect? I would expect the same order as `beforeAll_` and `afterAll_`:

```haskell
import Test.Hspec

aroundWithFn action () = do
  putStrLn "aroundWith before"
  action ()
  putStrLn "aroundWith after"

main = hspec $ aroundWith aroundWithFn $ afterAll_ (putStrLn "afterAll") $ beforeAll_ (putStrLn "beforeAll") $ do
  it "does item A" $ 2 `shouldBe` 2
  it "does item B" $ 2 `shouldBe` 2
```

```
aroundWith before
beforeAll
aroundWith after
does item A
aroundWith before
aroundWith after
does item B
aroundWith before
afterAll
aroundWith after
```

I think my `aroundAllWith` is consistent with this. :heavy_check_mark:  (Which you would expect because it's implemented in terms of those `beforeAllWith` and `afterAll`.)

I think the problem is the _conceptual sneakiness_ of combining the `all` functions with the non-`all` functions. Nesting is working, but `all` inherently only performs its action at the beginning and the end. So by mixing the two together you're setting yourself up for surprising results.

**Comment by NorfairKing** [comment]
@chrisdone Just as an aside, https://github.com/NorfairKing/sydtest supports `aroundAll`.

**Comment by sol** [comment]
@chrisdone Hey! This looks great! I'm eager to add your code to `Test.Hspec.Core.Hooks`.

I opened a PR based on your code (https://github.com/hspec/hspec/pull/472) + added some tests.

Three minor things I adjusted (https://github.com/hspec/hspec/commit/ff2aec1e193a9f1d090102616f1b0c698bbecf99):
1. We signal the `blocker` thread to proceed with any *cleanup* in `afterAll`.  However, we don't block until cleanup has completed.  I think this can be addressed by storing a reference to `blocker` in an `MVar` (https://github.com/hspec/hspec/commit/ff2aec1e193a9f1d090102616f1b0c698bbecf99#diff-1ccecb07798bceb14d8678e22ae0de22389039dfa80651ba2b98f21302590ac5R144) and then do a `takeMVar blorkerRef >>= wait` in `afterAll` (https://github.com/hspec/hspec/commit/ff2aec1e193a9f1d090102616f1b0c698bbecf99#diff-1ccecb07798bceb14d8678e22ae0de22389039dfa80651ba2b98f21302590ac5R158).
2. We silently ignore any exceptions from the *cleanup* part.  The fix for (1) addresses this too.
3. If the *resource acquire* part throws an exception then that exception will be correctly propagated due to the `link blocker`.  However, it will be wrapped in `ExceptionInLinkedThread`.  This is mostly cosmetic and I think can be easily fixed by catching, unwrapping and rethrowing (https://github.com/hspec/hspec/commit/ff2aec1e193a9f1d090102616f1b0c698bbecf99#diff-1ccecb07798bceb14d8678e22ae0de22389039dfa80651ba2b98f21302590ac5R156).

I'm hoping to push this to Hackage within the next 1-2 days.  Feedback very much welcome!
