### ISSUE TITLE
Documentation of possible arguments for --skip and --match

### ISSUE THREAD

**Issue by hpdeifel** [hspec/hspec#264]
The only documentation for `--match` that I can find is

> only run examples that match given PATTERN

with no description of what `PATTERN` may be. From hspec's tests, I see that some kind of hirarchical/structure is allowed. Is that all?

**Comment by dcastro** [comment]
From what I've tested so far, it seems a comma-separated list is interpreted as a hierarchical path, but it seems to be a bit buggy.

```hs
spec :: Spec
spec = 
    describe "main" $ do
        describe "x" $
            it "a" $ True `shouldBe` True
        describe "yy" $
            it "a" $ True `shouldBe` True
        describe "z z" $
            it "a" $ True `shouldBe` True
```

It seems like paths only work if a nested `describe` contains more than one word (e.g. `z z`), but not if it's only one word with no whitespace (e.g. `x`, `yy`)

```
λ> :main -m "main, x"      // doesn't run any tests

λ> :main -m "main, yy"    // doesn't run any tests

λ> :main -m "main, z z"
My.Module
  main
    z z
      a
```

@sol, could you please enlighten us?

Also, can you do "exact matches", or something similar to regex anchors, so that `main, something` will match `it "something"` but NOT `it "something else"`?

**Comment by sol** [comment]
@dcastro @hpdeifel sorry for the late reply.  This should definitely be discussed in the docs (PRs welcome of course).

There are two things that `-m` matches against.

1. the formated path, as show in error messages
2. all path components separated by `/`

Example:

```haskell
import           Test.Hspec

main :: IO ()
main = hspec $ do
  describe "Prelude" $ do
    describe "reverse" $ do
      it "reverses a list" False
      it "something else" True
```

When I run this spec I will see the following failure:

```
Failures:

  test/Spec.hs:9: 
  1) Prelude.reverse reverses a list
```

If I want to run the failing spec only, I have two options:

1. copy & paste the formated path and pass it to `-m`, specifically `-m Prelude.reverse reverses a list`
2. pass the path components separated by `/` to `-m`, specifically `-m "Prelude/reverse/reverses a list"`

**Comment by sol** [comment]
> It seems like paths only work if a nested describe contains more than one word

@dcastro this is due to Hspec assuming that single words denote function or module names, which are joined with a `.` rather than `, ` in the formatted path.

> I'm working on some tooling that interacts with hspec

Probably stating the obvious, for this use case your really only want to use (2) (separate the path components by `/`).

> Also, can you do "exact matches", or something similar to regex anchors, so that main, something will match it "something" but NOT it "something else"?

I think currently we always do substring matching, but I'm open to add this.  If you want this please open a separate issue.  I can offer to implement it in exchange of a documentation patch :laughing:.

**Comment by sol** [comment]
Here are the corresponding specs for the matching logic: https://github.com/hspec/hspec/blob/987ffd185f6a773a9a11cbbc88788174eff111b6/hspec-core/test/Test/Hspec/Core/UtilSpec.hs#L68

As a side note, there is this "is ambiguous" spec item, which basically says that we can't currently distinguish

```haskell
describe "foo" $ do
  it "bar/baz" $ do
    ...
```
from
```haskell
describe "foo" $ do
  describe "bar" $ do
    it "baz" $ do
```
(both will match `-m "foo/bar/baz"`)

If we wan't this, it certainly can be done, but we would need to escape one way or the other.

**Comment by dcastro** [comment]
Thanks a bunch @sol! The `/` separated paths work really well.

Also, regarding my question about exact matches, it looks like `/` paths do that as well :D :D

```hs
describe "main" $ do
    describe "something" $
        it "a" $ True `shouldBe` True
    describe "something else" $
        it "a" $ True `shouldBe` True
```

```
λ> :main -m "/something/"

My.Module
  main
    something
      a

Finished in 0.0007 seconds
1 example, 0 failures
```

This seems to fit my use case perfectly. I'm not too bothered by the ambiguous `/` scenario, I think I can work around that and I reckon it's an extremely unlikely edge case.

I'll play around with this a bit more, and will submit a documentation PR later! Thanks again!

**Comment by sol** [comment]
I finally added this to the docs https://hspec.github.io/match.html.
