### ISSUE TITLE
possible compile error because of inconsistency of HasCallStack

### ISSUE THREAD

**Issue by debug-ito** [hspec/hspec#283]
I tried to build `hspec-2.3.0` with stack. I used the following `stack.yaml` configuration.

- resolver: lts-7.0 (GHC 8.0.1)
- extra-deps:

    - hspec-2.3.0
    - hspec-core-2.3.0
    - hspec-discover-2.3.0
    - hspec-expectations-0.8.0
    - call-stack-0.1.0
    - QuickCheck-2.9.2

and I got the following error while compiling Test.Hspec.QuickCheck.

    /tmp/stack6684/hspec-2.3.0/src/Test/Hspec/QuickCheck.hs:27:10: error:
        Ambiguous occurrence ‘HasCallStack’
        It could refer to either ‘Data.CallStack.HasCallStack’,
                                 imported from ‘Data.CallStack’ at src/Test/Hspec/QuickCheck.hs:13:1-31
                                 (and originally defined in ‘GHC.Stack.Types’)
                              or ‘Test.Hspec.HasCallStack’,
                                 imported from ‘Test.Hspec’ at src/Test/Hspec/QuickCheck.hs:15:1-27
                                 (and originally defined in ‘Test.Hspec.Expectations’)

So there are two `HasCallStack` definitions, one in Data.CallStack and one in Test.Hspec.Expectations. Thanks to the CPP macro in Test.Hspec.Expectations, the build succeeds when I put HUnit-1.4.0.0 to extra-deps (the version from lts-7.0 is HUnit-1.3.1.2, and it's allowed by build-depends of hspec).

I'm not sure how we can fix this, but I think it's a little odd that Test.Hspec.Expectations has its own HasCallStack definition. Shouldn't Data.CallStack be the one and only compatibility layer??

**Comment by sol** [comment]
Thanks for reporting this! It's fixed on Hackage now. The whole thing is a little bit messy, due to backwards compatibility. `call-stack` is a compatibility shim for GHC-8's `HasCallStack`, but we can only use it when building against `HUnit >= 1.4`. The reason for that is that GHC-8 uses `?callStack` as the name for the implicit param, but older versions of `HUnit` use `?loc`.

For this reason `hspec-expectations` either re-exports or defines `HasCallStack` depending on the version of `HUnit`.

**Comment by debug-ito** [comment]
Thanks for the quick reply and explanation.
So at least the latest versions of packages all use Data.CallStack. That's cool.
