### ISSUE TITLE
Nicer output like test-framework?

### ISSUE THREAD

**Issue by bitemyapp** [hspec/hspec#333]
Had a reader of the book cite test-framework's output as being prettier than Hspec's. Might be worth amending it a bit to be easier to read.

From: https://batterseapower.github.io/test-framework/

![example test framework output](https://user-images.githubusercontent.com/320177/31730220-eaad2b3a-b3f6-11e7-9ee0-e4b98bdc7fd3.png)

**Comment by sol** [comment]
@bitemyapp Hi, thanks for taking the time to open this issue.  The next version of `hspec` will provide a reworked API for formatters and I'm also trying to figure out how to make it more convenient to use custom third-party formatters.  Currently a third-party formatter has to be added to the `.cabal` or `package.yaml` so that it can be used, which is not the most practical thing to do if different people working on the same code want to use different formatters.  I'm not yet sure how, but I hope to address this in some way in `stack` / `tinc` / `hpack`.

This is currently on the top of my Hspec priority list, but I'm also open to specific suggestion on what exactly we want to cherry-pick from `test-framework`.

**Comment by sol** [comment]
`2.7.10` introduced the new `checks` formatter:

![`checks` formatter](https://user-images.githubusercontent.com/461132/114891182-dccfe700-9e35-11eb-9435-82fae8ca870b.gif)

(use with `--format checks`)

This will be the default formatter for the upcoming `2.8.0` release.

I'm closing this, but please feel free to open separate issues with specific suggestions on how to make the output nicer.
