### ISSUE TITLE
Make colourful output per line

### ISSUE THREAD

**Issue by ip1981** [hspec/hspec#346]
hspec should set colour right before printing colourful line and reset it right after.

Currently it seems output multiple lines with colour and this breaks wrappers like timestamps in Jenkins (timestamps become colourful too).

![hspec-color](https://user-images.githubusercontent.com/131844/35326800-76d02b34-0100-11e8-935b-1120da121a18.png)

**Comment by ip1981** [comment]
For some reason github fails to upload a file: https://paste.ec/paste/OYdyDcTE#t9sv5d9MWxUh9WMeMxld+v8cFuUMjBz++3Q47nM2ztP

**Comment by robx** [comment]
Ran into the same issue on buildkite.

<img width="470" alt="Screenshot 2022-01-12 at 18 49 32" src="https://user-images.githubusercontent.com/132113/149221330-9390f39e-a4a0-447f-88d6-3ddd2564c6ff.png">

I made #605 to address this, though I'm not really sure it's entirely comprehensive.

In that screenshot above, not only does the color bleed into the timestamp prefixes. Buildkite also doesn't pick up on the `--- ` line prefix which it usually uses to segment the logs. While #605 ensures that there's no longer a "color reset" after the final newline, we'll still have the output end with `\n\ESC[?25h`, since hspec wraps its colored output in `cursor off`, `cursor on` globally.

Ideally, output would end with a `\n`, but is that really something hspec should need to worry about, or is it rather a limitation in these tools?

**Comment by sol** [comment]
> we'll still have the output end with `\n\ESC[?25h`, since hspec wraps its colored output in `cursor off`, `cursor on` globally.

@robx I addressed this for GitHub actions in 1ee36756 (disabling both progress reporting and cursor hiding).  I'm happy to do something similar for Buildkite.

**Comment by sol** [comment]
I opened https://github.com/hspec/hspec/pull/644.

**Comment by sol** [comment]
This will be available in `hspec-2.9.6` which is about to be released (pending CI, https://github.com/hspec/hspec/pull/651).

**Comment by sol** [comment]
It turns out that in diff output we sometimes need to colorize line breaks: #714, #660
