### ISSUE TITLE
Minor diff highlighting bug

### ISSUE THREAD

**Issue by ch3pjw** [hspec/hspec#351]
Consider the following, deliberately failing spec:
```haskell
spec :: Spec
  it "should demonstrate an Hspec highlighting bug" $
    "\NUL" `shouldBe` "\NULH"
```
The characters in the failure report output to the terminal are correct:
```
test/Lib/LibSpec.hs:12: 
  1) Lib.Lib should demonstrate an Hspec highlighting bug
       expected: "\NULH"
        but got: "\NUL"
```
However, the helpful colourful diff highlighting is not what I would expect. When I run the above, `ULH` is shown in red for the expected value, and `UL` in green for the "got" value. This is not minimal! I would have expected nothing to be highlighted in the bottom "got" string, and only the single additional `H` to be in red in the expected string.

**Comment by sol** [comment]
@ch3pjw thanks for reporting this!

Hspec's `--diff` is word based rather than character based (as diffing two lists of characters gives poor results frequently).  As it's quite common to diff strings, we treat things that look like backslash escapes as word boundaries.  So far this did not take multi-character escapes like `\NUL` into account.  I expanded this so that all character escapes that can be produced by the `Show` instance of `Char` are handled correctly.

As a side note, `--diff` is a best effort approach that makes assumptions about the input it deals with. As I see it there is no one correct solution and it will fall apart when confronted with pathological corner cases.
