### ISSUE TITLE
Installation for Newbs pls

### ISSUE THREAD

**Issue by Geroxus** [hspec/hspec#409]
Im very sorry i have to ask this, but i couldnt figure out how to install hspec.
Since its needed to run the tests provided by codewars I expected it to just neatly be copied somwhere on the harddrive and run from the folder to install itself in the paths or something.
Figures it doesn't.
Also all those codes `cabal update && cabal install hspec` just produce errors in every so beloved Haskell fashion.
So please give a quick rundown on how to install hspec somwhere.
Thanks for your time up to this point already.

**Comment by rozaxe** [comment]
I do not know if this is still relevant, but I fixed the problem with adding a `test-suite` in my `.cabal` file and then run `cabal test`.

Full exemple :
```
cabal-version:       >=1.10

name:                learning
version:             0.1.0.0
license-file:        LICENSE
author:
maintainer:
build-type:          Simple
extra-source-files:  CHANGELOG.md

executable learning
  main-is:             Main.hs
  build-depends:       base >=4.12 && <4.13
  default-language:    Haskell2010

-- The important one
test-suite test-main
  type:               exitcode-stdio-1.0
  main-is:            Spec.hs
  -- dependencies : hspec and QuickCheck for *arbitrary* tests
  build-depends:      base >=4.12 && <4.13,
                      hspec,
                      QuickCheck
--  End
```

**Comment by sol** [comment]
@Geroxus I updated the docs so that all the examples work with recent versions of `cabal`.

Basically, you need to run `cabal update && cabal install --package-env=. --lib hspec hspec-contrib QuickCheck HUnit` first.  After that you can use `ghci` or `runhaskell` in the current working directory.

For anything real, you want to create a Haskell package.  You can use https://github.com/hspec/hspec-example as a skeleton.

As for `codewars` I can't help with that.
