### ISSUE TITLE
diff algorithm is quadratic and hangs basically forever for long outputs

### ISSUE THREAD

**Issue by nh2** [hspec/hspec#415]
We encountered a situation where a test run just hung with 100% CPU at

```
  /path/to/Filehs:123:4: 
  1) My.Module It works expected
       expected: 
```

After some investigation, we found that the string that would have been printed in the following `but got:` output is `114883` many chars long.

In this case, the diff algorithm, runs so long that an output is never printed.

Some quick benchmarking shows a quadratic relationship:

```
chars  seconds
20000  17.5
15000  10
13000   7
10000   4
```

The `diff` algorithm is invoked here:

https://github.com/hspec/hspec/blob/3c748d47733da17dbe996a37e7ad6ed7b27b75fc/hspec-core/src/Test/Hspec/Core/Formatters.hs#L217

And its docs here

https://github.com/hspec/hspec/blob/3c748d47733da17dbe996a37e7ad6ed7b27b75fc/hspec-core/vendor/Data/Algorithm/Diff.hs#L11-L14

mention _O(N*D)_ complexity, [where](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.4.6927)

> two sequences A and B
> O(ND) time [complexity]
> where
> * N is the sum of the lengths of A and B and
> * D is the size of the minimum edit script for A and B

If `N` is the length of the string (e.g. 114883 in my case), and the edit script is _O(N)_ for the worst-case that most chars are missing, we end up with _O(N²)_.

Can you confirm this is the case?

**Comment by nh2** [comment]
If yes, we probably want to automatically turn off diffing for Strings longer than a certain length.

**Comment by nh2** [comment]
What I don't get is that it says that UNIX `diff` also implements this algorithm.

However, I've never noticed `diff` performing badly even on huge input files (where the second file is very short, like in our scenario).

For example,

```
$ head testfile
a
a
a
a

$ wc -l testfile
33554432 testfile

$ cat test2
a
b
c
a

 % time diff -u testfile test2 | wc -l
33554437
diff -u testfile test2  1,70s user 0,45s system 93% cpu 2,309 total
```

If `diff` was equally quadratic, this should have taken forever, but it did not.

Am I missing something?

**Comment by sol** [comment]
This is related to https://github.com/hspec/hspec/issues/331.

@nh2 I've been looking into this before and noticed the performance difference between GNU diff and the Haskell `Diff` package (which we are including).  What I didn't notice is that `Diff`s complexity is indeed what is documented.  Thanks a lot for pointing this out!

So far I always assumed that `Diff` is borked somehow, but profiling didn't reveal anything.

@cuklev tried something in https://github.com/hspec/hspec/pull/394, but it turned out that this is not a clear improvement.  This is why I've hesitated to merge it.

I think the ideal solution would be to implement a diff algorithm in Haskell that is on par with GNU diff.  I don't have the bandwidth to do so myself (for medical reasons).

@nh2 if you are interested to work on this then I can offer a symbolic bounty of USD 200 for a solution that satisfies the following requirements:

- It should work in the context of Hspec supporting something akin to `getGroupedDiff :: [String] -> [String] -> [Diff [String]]`  (that is: a solution that only works with `Strings` is ok, but ideally we will be able to continue to work with groups of `String`s)
- Pure Haskell if possible
- Tested with `nanospec` (doing so prevents a dependency cycle and will still allow for using `hspec` with `sensei` or `ghcid` during development)
- Hosted on GitHub or GitLab (ask if you would like to use something else)
- Commitment to maintain the implementation as a separate Haskell package
- PR for `hspec` in case changes to `hspec` are needed

(to claim the bounty you will need to provide bank account details; any bank account should do, but no PayPal)

**Comment by sol** [comment]
> we probably want to automatically turn off diffing for Strings longer than a certain length

The thing is that huge strings that have a small edit distance can be diffed just fine.  In a perfect wold we would short-circuit at the point where we exceed some predefined cpu/memory limit.

**Comment by gbaz** [comment]
GNU diff is based on the Meyers algorithm, but it by default has a number of optimizations turned on that provide non-minimal output but with improved performance. I don't know of a source that documents these well, but they are sketched in the manual (search the word "minimal"): https://www.gnu.org/software/diffutils/manual/diffutils.pdf

**Comment by AleXoundOS** [comment]
It would be good for the cba3332 to land in hackage.

**Comment by sol** [comment]
We now have the timeout.  That's not a prefect solution, but I'm not sure what else we can do.

If somebody wants to implement a more efficient diff algorithm that that would be great of course.   I'll not have the resources to do it myself however.

An other option would be to shell out and use whatever is on the `PATH` or make it configurable.

Not sure what's the best approach.

As things are there is no clean option forward, this is why I'll close this for now.

If anybody has specific suggestions or requests, then please don't be shy to open a new issue.

**Comment by AleXoundOS** [comment]
> An other option would be to shell out and use whatever is on the PATH or make it configurable.

Indeed. Is it possible to utilize an external `diff` program for this? If so, it needs a new issue.

**Comment by sol** [comment]
@AleXoundOS good point! I opened https://github.com/hspec/hspec/issues/514.

**Comment by sol** [comment]
`hspec-2.10.6` adds support for `--diff-command` and a corresponding environment variable + configuration file option.

Try setting
```bash
HSPEC_DIFF_COMMAND="diff -u --color -L expected -L actual"
```
for GNU di diff, or pass
```bash
--diff-command="git diff"
```
to use `git diff`.

https://github.com/hspec/hspec/pull/739 has screenshots that compare the options.
