### ISSUE TITLE
Long running property test status < 100 tests

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [hspec/hspec#426]
If there is a property test that has less than the standard 100 tests and is long running then the fractional test counter (ex. 2/100) reports the wrong number of tests with an extra zero.

If 10 tests are specified, I would expect the denominator to always be 10, like `x/10`.
Instead, the denominator is always 100, like `x/100`.

To r
```haskell
import Control.Concurrent
import Test.Hspec
import Test.QuickCheck

spec :: Spec
spec = do
    it "time out" $ withMaxSuccess 10 $ property $ \(x :: Int) -> ioProperty $ do
      threadDelay 1000000
      pure $ x `shouldBe` x
```

**Comment by BebeSparkelSparkel** [comment]
@sol Thanks

**Comment by sol** [comment]
@BebeSparkelSparkel it turned out that this was merely a formatter bug.  For some reason QuickCheck always reports `0/100` as the first progress.  Subsequently, when `1/10` was reported, we did not clear the existing output properly, so that it was displayed as `1/100`, as the last `0` was not clear from the screen.

BTW, this was only an issue when using `withMaxSuccess`.  Using command-line flags or the primitives from `Test.Hspec.QuickCheck` to modify `maxSuccess` did not suffer from this issue.

**Comment by BebeSparkelSparkel** [comment]
That's somewhat comic. It's reporting the correct value but previous printing screwed it up. Seems like a problem from the 80s lol. Appreciate you tracking that down, it had me confused for a while because usually the problem is me.
