### ISSUE TITLE
Change default formatter to `checks` with 2.8.0

### ISSUE THREAD

**Issue by sol** [hspec/hspec#489]
`hspec-2.7.10` adds a new `checks` formatter:

![`checks` formatter](https://user-images.githubusercontent.com/461132/114891182-dccfe700-9e35-11eb-9435-82fae8ca870b.gif)

I'm inclined to make this the default for `2.8.0`.  Opinions?

/cc @mklinik @soenkehahn

**Comment by soenkehahn** [comment]
I like this, great work! There is a chance that there's people who depend on the output format not changing, because they somehow process it programmatically. I personally think `hspec` should have the liberty to improve the output format. Also `2.8.0` would communicate that it includes breaking changes, so I think it should be fine. So LGTM!
