### ISSUE TITLE
`hspec-discover-2.8.4` fails to build on GHC 7.0

### ISSUE THREAD

**Issue by RyanGlScott** [hspec/hspec#554]
As seen in [this failing GHC 7.0 CI job](https://github.com/nfrisby/invariant-functors/runs/4137153952?check_suite_focus=true#step:17:38), `hspec-discover-2.8.4` fails to build on GHC 7.0:

```
Building library for hspec-discover-2.8.4..
ghc: unrecognised flags: -fno-warn-incomplete-uni-patterns
```

On the other hand, `hspec-discover-2.8.3` _does_ build with 7.0, so this was most likely introduced in commit 7f85d0721829da8968c34aeb0f8d55064077dddc. (Note that `-fwarn-incomplete-uni-patterns` was [introduced in GHC 7.2](https://downloads.haskell.org/ghc/9.2.1/docs/html/users_guide/using-warnings.html#ghc-flag--Wincomplete-uni-patterns).)

Can you either:

1. Apply a Hackage revision to `hspec-discover-2.8.4` to mark that it is unbuildable with GHC 7.0 (e.g., `base >= 4.4`), or
2. Push a new version of `hspec-discover` that guards the use of `-fno-warn-incomplete-uni-patterns` with CPP? Something like this, perhaps:

   ```hs
   #if __GLASGOW_HASKELL__ >= 702
   {-# OPTIONS_GHC -fno-warn-incomplete-uni-patterns #-}
   #endif __GLASGOW_HASKELL__ >= 702
   ```

I'm not sure which approach you'd prefer, but either should work. Thanks!

**Comment by sol** [comment]
https://hackage.haskell.org/package/hspec-discover-2.8.4/revisions/

**Comment by sol** [comment]
`hspec-discover-2.8.4` should only be used with `hspec-2.8.4`, which already has versions bounds on `base` so that imply GHC >= 7.4.*.

I think the underlying issue is that there is no way to teach `cabal-install` to use a matching version of `hspec-discover` without specifying exact versions (at least not that I'm aware of).  This used to work in the past but was broken by `v2-*`.

**Comment by RyanGlScott** [comment]
That works for me. Thanks!
